# Generated by Django 2.2.3 on 2019-08-09 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('remaining_accesses', models.IntegerField(default=0)),
                ('expiration_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, unique=True, upload_to='<django.db.models.fields.AutoField>.jpg')),
                ('log_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfid.RFIDCard')),
            ],
        ),
    ]
